publish_to: none

name: engine_io_shared
version: 0.1.0

description: Shared dependency of the engine.io server and client.

homepage: https://github.com/WordCollector/engine_io/tree/main/packages/shared
repository: https://github.com/WordCollector/engine_io/tree/main/packages/shared
issue_tracker: https://github.com/WordCollector/engine_io/tree/main/packages/shared/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.3 # Cryptography functions. (Only `sha1` is used.)

dev_dependencies:
  # Precise versions are specified in the monorepo.
  test: any # Testing.
  words: any # Lints.