publish_to: none

name: engine_io_shared
version: 0.1.0

description: Shared dependency of the engine.io server and client.

homepage: https://github.com/wordcollector/engine_io
repository: https://github.com/wordcollector/engine_io
issue_tracker: https://github.com/wordcollector/engine_io/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  import_sorter: ^4.6.0 # Sorting imports.
  words: ^0.4.0 # Lints.

import_sorter:
  comments: false