publish_to: none

name: engine_io
version: 0.1.0

description: Monorepo for the engine.io client, server and shared dependencies.

homepage: https://github.com/wordcollector/engine_io
repository: https://github.com/wordcollector/engine_io
issue_tracker: https://github.com/wordcollector/engine_io/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  import_sorter: ^4.6.0 # Sorting imports.
  melos: ^3.1.0 # Managing the monorepo.
  test: ^1.24.3 # Testing.
  words: ^0.4.2 # Lints.

import_sorter:
  comments: false