publish_to: none

name: engine_io_dart
version: 0.1.0

description: A Dart implementation of engine.io.

homepage: https://github.com/wordcollector/engine_io_dart
repository: https://github.com/wordcollector/engine_io_dart
issue_tracker: https://github.com/wordcollector/engine_io_dart/issues

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  crypto: ^3.0.3 # Cryptography functions. (`sha1` is used.)
  meta: ^1.9.1 # Static code analysis.
  universal_io: ^2.2.0 # Cross-platform dart:io.
  uuid: ^3.0.7 # Unique identifiers for socket connections. (`v4` is used.)

dev_dependencies:
  test: ^1.24.2 # Testing.
  words: ^0.2.0 # Lints.
