publish_to: none

name: engine_io_server
version: 0.1.0

description: >-
  A purely Dart implementation of the engine.io server,
  made with quality and correctness in mind.

homepage: https://github.com/WordCollector/engine_io/tree/main/packages/server
repository: https://github.com/WordCollector/engine_io/tree/main/packages/server
issue_tracker: https://github.com/WordCollector/engine_io/tree/main/packages/server/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  engine_io_shared:
    path: ../shared
  uuid: ^3.0.7 # Unique identifiers for socket connections. (`v4` is used.)

dev_dependencies:
  async: ^2.11.0 # Testing streams.
  # Precise versions are specified in the monorepo.
  test: any # Testing.
  words: any # Lints.
