publish_to: none

name: engine_io_server
version: 0.1.0

description: >-
  A purely Dart implementation of the engine.io server,
  made with quality and correctness in mind.

homepage: https://github.com/wordcollector/engine_io
repository: https://github.com/wordcollector/engine_io
issue_tracker: https://github.com/wordcollector/engine_io/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.3 # Cryptography functions. (`sha1` is used.)
  meta: ^1.9.1 # Static code analysis.
  universal_io: ^2.2.0 # Cross-platform dart:io.
  uuid: ^3.0.7 # Unique identifiers for socket connections. (`v4` is used.)

dev_dependencies:
  async: ^2.11.0 # Testing streams.
  import_sorter: ^4.6.0 # Sorting imports.
  test: ^1.24.2 # Testing.
  words: ^0.4.0 # Lints.

import_sorter:
  comments: false